stages:
    - code
    - build
    - deploy
    - docs

variables:
    GITLAB_REGISTRY_ID: 43895499
    DOCKER_DRIVER: overlay2

.node16:
    image: node:16-alpine
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - .npm/
    before_script:
        - npm ci --cache .npm --prefer-offline
    only:
        - tags

test:
    stage: code
    extends: .node16
    script:
        - npm run test
    artifacts:
        when: always
        reports:
            junit: ./reports/junit/junit.xml

lint:
    stage: code
    extends: .node16
    script:
        - npm run lint

compile:
    stage: build
    extends: .node16
    script:
        - npm run build
    artifacts:
        name: compile
        paths:
            - build
package:
    stage: deploy
    image: node:14.17
    script:
        - npm config set @danny270793:registry https://${CI_SERVER_HOST}/api/v4/projects/${GITLAB_REGISTRY_ID}/packages/npm/
        - npm config set -- '//${CI_SERVER_HOST}/api/v4/projects/${GITLAB_REGISTRY_ID}/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
        - npm publish
    dependencies:
        - compile
    only:
        - tags

pages:
    stage: docs
    extends: .node16
    script:
        - npm run documentate
    artifacts:
        paths:
            - ./public
